[workspace]
members = ["bot", "modules/*"]
resolver = "2"
default-members = ["bot"]

[workspace.dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
dotenv = "0.15.0"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
tranquil = { git = "https://github.com/Possseidon/tranquil", rev = "e7e86617503ac0d37901a37044049dc2790d207e" }
