[workspace]
members = ["bot", "games/*", "modules/*"]
resolver = "2"
default-members = ["bot"]

[workspace.dependencies]
async-trait = "0.1.73"
dotenv = "0.15.0"
tokio = { version = "1.32.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
tranquil = "0.2.0"
