[package]
name = "ping-module"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.73"
tokio = { version = "1.26", features = ["macros", "rt-multi-thread", "signal"] }
tranquil = "0.2.0"
