[package]
name = "ping-module"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.11.5"
tokio = { version = "1.24", features = ["macros", "rt-multi-thread", "signal"] }
tranquil = "0.2.0"
