[package]
name = "bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
dotenvy = { workspace = true }
tokio = { workspace = true }
tranquil = { workspace = true }

db = { path = "../backend/db" }
ping-module = { path = "../modules/ping-module" }
