[package]
name = "bot"
version = "0.1.0"
edition = "2021"

[dependencies]
ping-module = { path = "../modules/ping-module" }
dotenv = "0.15.0"
serenity = "0.11.5"
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread", "signal"] }
tranquil = "0.2.0"
